FROM python:3.10
EXPOSE 3000-9000
WORKDIR /src
COPY ./backend/requirements.txt .
RUN apt update && apt upgrade -y 
RUN curl -fsSL https://bun.com/install | bash
RUN pip install --upgrade pip && pip install -Ur requirements.txt

